Fix a view maintenance failure due to a missing subquery alias
With PostgreSQL 15 or earlier, view maintenance failed with
the following error:

ERROR:  subquery in FROM must have an alias

This bug was introduced in 48c71bbab.